### ISSUE TITLE
Run tim error

### ISSUE THREAD

**Issue by brightonguy** [themagpimag/magpi-epub-generator#2]
When running with Python 2.7.3 on windows 7 x64, I get the following:
Creating issue 7
Adding: Raspberry Pi &amp; Arduino
Found image: http://www.themagpi.com/assets/arduino-serial_menu.png
Found image: http://www.themagpi.com/assets/arduino-board_menu.png
Found image: http://www.themagpi.com/assets/ArduinoFirmata_bb-300x157.png
Adding: Traceback (most recent call last):
  File "make_epub.py", line 141, in <module>
    e.make(issue)
  File "make_epub.py", line 128, in make
    print 'Adding:', article.title
  File "C:\Python27\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2026' in position 24: character maps to <undefined>
1.  Can I correct this
2. Could I start at issue 8?

I am a complete Python NOOB.

**Comment by mattjudge** [comment]
Should now be fixed
