### ISSUE TITLE
Conversion fails on Issue 14

### ISSUE THREAD

**Issue by brightonguy** [themagpimag/magpi-epub-generator#3]
Thanks for the last fix. It now fails getting issue 14:

Creating issue 14

Traceback (most recent call last):
  File "D:\Util\magpi-epub-generator-master\make_epub.py", line 151, in <module>
    e.make(issueObj)
  File "D:\Util\magpi-epub-generator-master\make_epub.py", line 132, in make
    articles = issue.get_articles()
  File "D:\Util\magpi-epub-generator-master\mps_api.py", line 83, in get_articles
    self.articles = Articles(self.id)
  File "D:\Util\magpi-epub-generator-master\mps_api.py", line 157, in **init**
    self.articles.append(Article(article))
  File "D:\Util\magpi-epub-generator-master\mps_api.py", line 107, in **init**
    Post.**init**(self, data)
  File "D:\Util\magpi-epub-generator-master\mps_api.py", line 42, in **init**
    self.id = data['id']
TypeError: string indices must be integers

From a bit of debug output (print "data->", data just before self.data = data in class Post()), it seems that data isn't what was expected - no info in data:
data-> {u'title': u'Issue 14', u'url': u'http://www.themagpi.com/issue/issue-14/', u'issuu': u'issue14final', u'cover': u'http://www.themagpi.com/assets/14. jpg', 'content': u'<p>Welcome to the 14th issue of The MagPi &#8211; another fully loaded guide to all things Raspberry Pi!</p>\n<p>This month we begin our journey in introducing the newest module in the Raspberry Pi world, the camera, with a great guide written by James Hughes on setup and basic operation.\xa0 The conclusion of this article will be found in next month&#8217;s edition where James builds on these foundations with hints and tips on advanced usage.</p>\n<p>We reload the Matrix with part two of the interesting Pi Matrix article, take a look at the Guzunty board and review the ever popular South West Raspberry Pi Boot Camps.</p>\n<p>We bring you more on the programming languages Charm, Scratch and Python plus bring you the first MagPi article on the popular language, Java.</p>\n<p>I am pleased to report that all pre-order Volume 1 MagPi bundles ordered via Kickstarter or <a href="http://themagpi.com" class="autohyperlink" title="http://themagpi.com" target="_blank">themagpi.com</a> have now shipped. We will soon have individual issues coming to print.\xa0 We hope you enjoy the printed editions and thank you again for your support and patience in helping make the dream a reality.</p>\n<p>Ash Stone</p>\n', 'header': None, u'editorial': u'<p>Welcome to the 14th issue of The MagPi &#8211; another fully loaded guide to all things Raspberry Pi!</p>\n<p>This month we begin our journey in introducing the newest module in the Raspberry Pi world, the camera, with a great guide written by James Hughes on setup and basic operation.\xa0 The conclusion of this article will be found in next month&#8217;s edition where James builds on these foundations with hints and tips on advanced usage.</p>\n<p>We reload the Matrix with part two of the interesting Pi Matrix article, take a look at the Guzunty board and review the ever popular South West Raspberry Pi Boot Camps.</p>\n<p>We bring you more on the programming languages Charm, Scratch and Python plus bring you the first MagPi article on the popular language, Java.</p>\n<p>I am pleased to report that all pre-order Volume 1 MagPi bundles ordered via Kickstarter or <a href="http://themagpi.com" class="autohyperlink" title="http://themagpi.com" target="_blank">themagpi.com</a> have now shipped. We will soon have individual issues coming to print.\xa0 We hope you enjoy the printed editions and thank you again for your support and patience in helping make the dream a reality.</p>\n<p>Ash Stone</p>\n', u'date': u'July 1, 2013', u'pdf': u'http://www.themagpi.com/issue/issue-14/pdf', u'id': 53}
data-> n

I also notice that it only gets up to issue 14. Is there a problem here?

Mant thanks

Mike

**Comment by mattjudge** [comment]
This is because issue 14 has not had any html versions of the articles uploaded to the MagPi website.

It should not have errored out like that though, and this has been fixed. If a range of issue values is given, the script should now simply pass over any issues with no articles available for compilation.

Thanks,
Matt
